print ("Sherpa Terminal Emulator Version 0.1")
print ("___________________")
print ("| 		  |")
print ("| //              |")
print ("|  //             |")
print ("|   //            |")
print ("|  //             |")
print ("| //              |")
print ("|                 |")
print ("|_________________|")
